{% set version = "87fd246" %}
{% set sha256 = "507f797707ec117163f818cc223d0913a7d2fa8c11bacc117dfcda6672443ebf" %}

package:
  name: reproblas
  version: "2.1.0"

source:
  url: https://github.com/zhihaoy/ReproBLAS/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.17
    - ninja
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/include/reproBLAS/reproBLAS_api.h          # [unix]
    - test -f ${PREFIX}/lib/cmake/reproBLAS/reproblas-config.cmake # [unix]
    - if exist %LIBRARY_PREFIX%\include\reproBLAS\reproBLAS_api.h (exit 0) else (exit 1)          # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\reproBLAS\reproblas-config.cmake (exit 0) else (exit 1) # [win]

about:
  home: https://bebop.cs.berkeley.edu/reproblas/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Reproducible Basic Linear Algebra Subprograms
  description: |
    ReproBLAS aims at providing users with a set of (Parallel and
    Sequential) Basic Linear Algebra Subprograms that guarantee
    reproducibility regardless of the number of processors, of the
    data partitioning, of the way reductions are scheduled, and
    more generally of the order in which the sums are computed.
  doc_url: https://bebop.cs.berkeley.edu/reproblas/documentation.php

extra:
  recipe-maintainers:
    - zhihao.yuan
